# fly.toml app configuration file generated for health-history on 2024-07-16T16:01:31+09:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'health-history'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  source = "pb_data"
  destination = "/app/pb/pb_data"